#
DROP PROCEDURE IF EXISTS spAlterStock;
#
DROP PROCEDURE IF EXISTS spNewSale;
#
DROP PROCEDURE IF EXISTS spPurchaseId;
#
DROP PROCEDURE IF EXISTS spSaleToPur;
#
DROP PROCEDURE IF EXISTS spSaleWorker;